name: Check
on: [push]
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Cache
        uses: actions/cache@v6
        with:
          key: ${{ runner.os  }}-key
          path: |
            .svelte-kit/**/*
            node_modules/**/*
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependency
        run: bun i --frozen-lockfile
      - name: Sync types
        run: bun sync
      - name: Check
        run: bun check
